name: vlc_remote
description: VLC remote control

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.8+2
  http: ^0.12.1
  just_throttle_it: ^1.0.0
  shared_preferences: ^0.5.7
  xml: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon-512.png
    - assets/cone.png
    - assets/signal-0.png
    - assets/signal-1.png
    - assets/signal-2.png
    - assets/signal-3.png
